# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

Country.create([
  { country_code: 'de', name: 'germany' },
  { country_code: 'fr', name: 'france' },
  { country_code: 'en', name: 'england' },
  { country_code: 'ru', name: 'russia' },
  { country_code: 'tr', name: 'turkey' },
  { country_code: 'it', name: 'italy' },
  { country_code: 'au', name: 'austria' }
])

Province.create([
  { 'province_code':'adr', 'name':'adriatic sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'aeg', 'name':'aegean sea', 'province_type':'coast', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'alb', 'name':'albania', 'province_type':'coast', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ank', 'name':'ankara', 'province_type':'coast', 'is_sc':1, 'home_of':'tr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'apu', 'name':'apulia', 'province_type':'coast', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'arm', 'name':'armenia', 'province_type':'coast', 'is_sc':0, 'home_of':'tr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bal', 'name':'baltic sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bar', 'name':'barents sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bel', 'name':'belgium', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ber', 'name':'berlin', 'province_type':'coast', 'is_sc':1, 'home_of':'de', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bla', 'name':'black sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'boh', 'name':'bohemia', 'province_type':'land', 'is_sc':0, 'home_of':'au', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bot', 'name':'gulf of bothnia', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bre', 'name':'brest', 'province_type':'coast', 'is_sc':1, 'home_of':'fr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bud', 'name':'budapest', 'province_type':'land', 'is_sc':1, 'home_of':'au', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'bul', 'name':'bulgaria', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':'sc', 'coast_2':'ec' },
  { 'province_code':'bur', 'name':'burgundy', 'province_type':'land', 'is_sc':0, 'home_of':'fr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'cly', 'name':'clyde', 'province_type':'coast', 'is_sc':0, 'home_of':'en', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'con', 'name':'constantinople', 'province_type':'coast', 'is_sc':1, 'home_of':'tr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'den', 'name':'denmark', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'eas', 'name':'eastern mediterranean', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'edi', 'name':'edinburgh', 'province_type':'coast', 'is_sc':1, 'home_of':'en', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'eng', 'name':'english channel', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'fin', 'name':'finland', 'province_type':'coast', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'gal', 'name':'galicia', 'province_type':'land', 'is_sc':0, 'home_of':'au', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'gas', 'name':'gascony', 'province_type':'coast', 'is_sc':0, 'home_of':'fr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'gre', 'name':'greece', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'hel', 'name':'helgoland bight', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'hol', 'name':'holland', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ion', 'name':'ionian sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'iri', 'name':'irish sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'kie', 'name':'kiel', 'province_type':'coast', 'is_sc':1, 'home_of':'de', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'lon', 'name':'london', 'province_type':'coast', 'is_sc':1, 'home_of':'en', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'lvp', 'name':'liverpool', 'province_type':'coast', 'is_sc':1, 'home_of':'en', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'lvn', 'name':'livonia', 'province_type':'coast', 'is_sc':0, 'home_of':'ru', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'lyo', 'name':'gulf of lyons', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'mar', 'name':'marseilles', 'province_type':'coast', 'is_sc':1, 'home_of':'fr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'mid', 'name':'mid-atlantic ocean', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'mos', 'name':'moscow', 'province_type':'land', 'is_sc':1, 'home_of':'ru', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'mun', 'name':'munich', 'province_type':'land', 'is_sc':1, 'home_of':'de', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'naf', 'name':'north africa', 'province_type':'coast', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'nap', 'name':'naples', 'province_type':'coast', 'is_sc':1, 'home_of':'it', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'nat', 'name':'north atlantic ocean', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'nrg', 'name':'norwegian sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'nth', 'name':'north sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'nor', 'name':'norway', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'par', 'name':'paris', 'province_type':'land', 'is_sc':1, 'home_of':'fr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'pic', 'name':'picardy', 'province_type':'coast', 'is_sc':0, 'home_of':'fr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'pie', 'name':'piedmont', 'province_type':'coast', 'is_sc':0, 'home_of':'it', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'por', 'name':'portugal', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'pru', 'name':'prussia', 'province_type':'coast', 'is_sc':0, 'home_of':'de', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'rom', 'name':'rome', 'province_type':'coast', 'is_sc':1, 'home_of':'it', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ruh', 'name':'ruhr', 'province_type':'land', 'is_sc':0, 'home_of':'de', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'rum', 'name':'rumania', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ser', 'name':'serbia', 'province_type':'land', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'sev', 'name':'sevastopol', 'province_type':'coast', 'is_sc':1, 'home_of':'ru', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'sil', 'name':'silesia', 'province_type':'land', 'is_sc':0, 'home_of':'de', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ska', 'name':'skagerrack', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'smy', 'name':'smyrna', 'province_type':'coast', 'is_sc':1, 'home_of':'tr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'spa', 'name':'spain', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':'sc', 'coast_2':'nc' },
  { 'province_code':'stp', 'name':'st. petersburg', 'province_type':'coast', 'is_sc':1, 'home_of':'ru', 'coast_1':'sc', 'coast_2':'nc' },
  { 'province_code':'swe', 'name':'sweden', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'syr', 'name':'syria', 'province_type':'coast', 'is_sc':0, 'home_of':'tr', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'tri', 'name':'trieste', 'province_type':'coast', 'is_sc':1, 'home_of':'au', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'tro', 'name':'tyrolia', 'province_type':'land', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'tun', 'name':'tunis', 'province_type':'coast', 'is_sc':1, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'tus', 'name':'tuscany', 'province_type':'coast', 'is_sc':0, 'home_of':'it', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'trn', 'name':'tyrrhenian sea', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ukr', 'name':'ukraine', 'province_type':'land', 'is_sc':0, 'home_of':'ru', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'ven', 'name':'venice', 'province_type':'coast', 'is_sc':1, 'home_of':'it', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'vie', 'name':'vienna', 'province_type':'land', 'is_sc':1, 'home_of':'au', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'wal', 'name':'wales', 'province_type':'coast', 'is_sc':0, 'home_of':'en', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'war', 'name':'warsaw', 'province_type':'land', 'is_sc':1, 'home_of':'ru', 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'wes', 'name':'western mediterranean', 'province_type':'sea', 'is_sc':0, 'home_of':nil, 'coast_1':nil, 'coast_2':nil },
  { 'province_code':'yor', 'name':'yorkshire', 'province_type':'coast', 'is_sc':0, 'home_of':'en', 'coast_1':nil, 'coast_2':nil }
])

ProvinceBorder.create([
  {'province_code':'adr', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'adr', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'adr', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'adr', 'border_province_code':'apu', 'border_coastal_code':nil},
  {'province_code':'adr', 'border_province_code':'alb', 'border_coastal_code':nil},
  {'province_code':'aeg', 'border_province_code':'gre', 'border_coastal_code':nil},
  {'province_code':'aeg', 'border_province_code':'bul', 'border_coastal_code':'sc'},
  {'province_code':'aeg', 'border_province_code':'con', 'border_coastal_code':nil},
  {'province_code':'aeg', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'aeg', 'border_province_code':'eas', 'border_coastal_code':nil},
  {'province_code':'aeg', 'border_province_code':'smy', 'border_coastal_code':nil},
  {'province_code':'alb', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'alb', 'border_province_code':'adr', 'border_coastal_code':nil},
  {'province_code':'alb', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'alb', 'border_province_code':'gre', 'border_coastal_code':nil},
  {'province_code':'alb', 'border_province_code':'ser', 'border_coastal_code':nil},
  {'province_code':'ank', 'border_province_code':'arm', 'border_coastal_code':nil},
  {'province_code':'ank', 'border_province_code':'bla', 'border_coastal_code':nil},
  {'province_code':'ank', 'border_province_code':'con', 'border_coastal_code':nil},
  {'province_code':'ank', 'border_province_code':'smy', 'border_coastal_code':nil},
  {'province_code':'apu', 'border_province_code':'adr', 'border_coastal_code':nil},
  {'province_code':'apu', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'apu', 'border_province_code':'rom', 'border_coastal_code':nil},
  {'province_code':'apu', 'border_province_code':'nap', 'border_coastal_code':nil},
  {'province_code':'apu', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'arm', 'border_province_code':'sev', 'border_coastal_code':nil},
  {'province_code':'arm', 'border_province_code':'bla', 'border_coastal_code':nil},
  {'province_code':'arm', 'border_province_code':'ank', 'border_coastal_code':nil},
  {'province_code':'arm', 'border_province_code':'syr', 'border_coastal_code':nil},
  {'province_code':'arm', 'border_province_code':'smy', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'lvn', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'pru', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'ber', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'den', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'swe', 'border_coastal_code':nil},
  {'province_code':'bal', 'border_province_code':'bot', 'border_coastal_code':nil},
  {'province_code':'bar', 'border_province_code':'stp', 'border_coastal_code':'nc'},
  {'province_code':'bar', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'bar', 'border_province_code':'nrg', 'border_coastal_code':nil},
  {'province_code':'bel', 'border_province_code':'hol', 'border_coastal_code':nil},
  {'province_code':'bel', 'border_province_code':'ruh', 'border_coastal_code':nil},
  {'province_code':'bel', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'bel', 'border_province_code':'pic', 'border_coastal_code':nil},
  {'province_code':'bel', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'bel', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'ber', 'border_province_code':'pru', 'border_coastal_code':nil},
  {'province_code':'ber', 'border_province_code':'sil', 'border_coastal_code':nil},
  {'province_code':'ber', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'ber', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'ber', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'bla', 'border_province_code':'sev', 'border_coastal_code':nil},
  {'province_code':'bla', 'border_province_code':'bul', 'border_coastal_code':'ec'},
  {'province_code':'bla', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'bla', 'border_province_code':'con', 'border_coastal_code':nil},
  {'province_code':'bla', 'border_province_code':'ank', 'border_coastal_code':nil},
  {'province_code':'bla', 'border_province_code':'arm', 'border_coastal_code':nil},
  {'province_code':'boh', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'boh', 'border_province_code':'sil', 'border_coastal_code':nil},
  {'province_code':'boh', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'boh', 'border_province_code':'vie', 'border_coastal_code':nil},
  {'province_code':'boh', 'border_province_code':'tro', 'border_coastal_code':nil},
  {'province_code':'bot', 'border_province_code':'swe', 'border_coastal_code':nil},
  {'province_code':'bot', 'border_province_code':'fin', 'border_coastal_code':nil},
  {'province_code':'bot', 'border_province_code':'stp', 'border_coastal_code':'sc'},
  {'province_code':'bot', 'border_province_code':'lvn', 'border_coastal_code':nil},
  {'province_code':'bot', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'bre', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'bre', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'bre', 'border_province_code':'gas', 'border_coastal_code':nil},
  {'province_code':'bre', 'border_province_code':'pic', 'border_coastal_code':nil},
  {'province_code':'bre', 'border_province_code':'par', 'border_coastal_code':nil},
  {'province_code':'bud', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'bud', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'bud', 'border_province_code':'ser', 'border_coastal_code':nil},
  {'province_code':'bud', 'border_province_code':'vie', 'border_coastal_code':nil},
  {'province_code':'bud', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'bul', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'bul', 'border_province_code':'con', 'border_coastal_code':nil},
  {'province_code':'bul', 'border_province_code':'ser', 'border_coastal_code':nil},
  {'province_code':'bul', 'border_province_code':'bla', 'border_coastal_code':'ec'},
  {'province_code':'bul', 'border_province_code':'aeg', 'border_coastal_code':'sc'},
  {'province_code':'bur', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'bur', 'border_province_code':'par', 'border_coastal_code':nil},
  {'province_code':'bur', 'border_province_code':'mar', 'border_coastal_code':nil},
  {'province_code':'bur', 'border_province_code':'gas', 'border_coastal_code':nil},
  {'province_code':'bur', 'border_province_code':'ruh', 'border_coastal_code':nil},
  {'province_code':'bur', 'border_province_code':'bel', 'border_coastal_code':nil},
  {'province_code':'bur', 'border_province_code':'pic', 'border_coastal_code':nil},
  {'province_code':'cly', 'border_province_code':'nat', 'border_coastal_code':nil},
  {'province_code':'cly', 'border_province_code':'nrg', 'border_coastal_code':nil},
  {'province_code':'cly', 'border_province_code':'edi', 'border_coastal_code':nil},
  {'province_code':'cly', 'border_province_code':'lvp', 'border_coastal_code':nil},
  {'province_code':'con', 'border_province_code':'bul', 'border_coastal_code':nil},
  {'province_code':'con', 'border_province_code':'bla', 'border_coastal_code':nil},
  {'province_code':'con', 'border_province_code':'ank', 'border_coastal_code':nil},
  {'province_code':'con', 'border_province_code':'smy', 'border_coastal_code':nil},
  {'province_code':'con', 'border_province_code':'aeg', 'border_coastal_code':nil},
  {'province_code':'den', 'border_province_code':'ska', 'border_coastal_code':nil},
  {'province_code':'den', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'den', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'den', 'border_province_code':'hel', 'border_coastal_code':nil},
  {'province_code':'den', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'den', 'border_province_code':'swe', 'border_coastal_code':nil},
  {'province_code':'eas', 'border_province_code':'smy', 'border_coastal_code':nil},
  {'province_code':'eas', 'border_province_code':'syr', 'border_coastal_code':nil},
  {'province_code':'eas', 'border_province_code':'aeg', 'border_coastal_code':nil},
  {'province_code':'eas', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'edi', 'border_province_code':'cly', 'border_coastal_code':nil},
  {'province_code':'edi', 'border_province_code':'lvp', 'border_coastal_code':nil},
  {'province_code':'edi', 'border_province_code':'yor', 'border_coastal_code':nil},
  {'province_code':'edi', 'border_province_code':'nrg', 'border_coastal_code':nil},
  {'province_code':'edi', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'wal', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'lon', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'bre', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'bel', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'pic', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'iri', 'border_coastal_code':nil},
  {'province_code':'eng', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'fin', 'border_province_code':'stp', 'border_coastal_code':nil},
  {'province_code':'fin', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'fin', 'border_province_code':'swe', 'border_coastal_code':nil},
  {'province_code':'fin', 'border_province_code':'bot', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'war', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'ukr', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'bud', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'vie', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'boh', 'border_coastal_code':nil},
  {'province_code':'gal', 'border_province_code':'sil', 'border_coastal_code':nil},
  {'province_code':'gas', 'border_province_code':'spa', 'border_coastal_code':nil},
  {'province_code':'gas', 'border_province_code':'bre', 'border_coastal_code':nil},
  {'province_code':'gas', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'gas', 'border_province_code':'par', 'border_coastal_code':nil},
  {'province_code':'gas', 'border_province_code':'mar', 'border_coastal_code':nil},
  {'province_code':'gas', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'gre', 'border_province_code':'aeg', 'border_coastal_code':nil},
  {'province_code':'gre', 'border_province_code':'bul', 'border_coastal_code':nil},
  {'province_code':'gre', 'border_province_code':'ser', 'border_coastal_code':nil},
  {'province_code':'gre', 'border_province_code':'alb', 'border_coastal_code':nil},
  {'province_code':'gre', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'hel', 'border_province_code':'den', 'border_coastal_code':nil},
  {'province_code':'hel', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'hel', 'border_province_code':'hol', 'border_coastal_code':nil},
  {'province_code':'hel', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'hol', 'border_province_code':'bel', 'border_coastal_code':nil},
  {'province_code':'hol', 'border_province_code':'ruh', 'border_coastal_code':nil},
  {'province_code':'hol', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'hol', 'border_province_code':'hel', 'border_coastal_code':nil},
  {'province_code':'hol', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'aeg', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'nap', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'adr', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'apu', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'eas', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'gre', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'alb', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'tun', 'border_coastal_code':nil},
  {'province_code':'ion', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'iri', 'border_province_code':'lvp', 'border_coastal_code':nil},
  {'province_code':'iri', 'border_province_code':'wal', 'border_coastal_code':nil},
  {'province_code':'iri', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'iri', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'iri', 'border_province_code':'nat', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'den', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'ber', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'ruh', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'hol', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'hel', 'border_coastal_code':nil},
  {'province_code':'kie', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'lon', 'border_province_code':'yor', 'border_coastal_code':nil},
  {'province_code':'lon', 'border_province_code':'wal', 'border_coastal_code':nil},
  {'province_code':'lon', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'lon', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'lvn', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'lvn', 'border_province_code':'stp', 'border_coastal_code':nil},
  {'province_code':'lvn', 'border_province_code':'mos', 'border_coastal_code':nil},
  {'province_code':'lvn', 'border_province_code':'bot', 'border_coastal_code':nil},
  {'province_code':'lvn', 'border_province_code':'war', 'border_coastal_code':nil},
  {'province_code':'lvn', 'border_province_code':'pru', 'border_coastal_code':nil},
  {'province_code':'lvp', 'border_province_code':'wal', 'border_coastal_code':nil},
  {'province_code':'lvp', 'border_province_code':'yor', 'border_coastal_code':nil},
  {'province_code':'lvp', 'border_province_code':'edi', 'border_coastal_code':nil},
  {'province_code':'lvp', 'border_province_code':'cly', 'border_coastal_code':nil},
  {'province_code':'lvp', 'border_province_code':'iri', 'border_coastal_code':nil},
  {'province_code':'lvp', 'border_province_code':'nat', 'border_coastal_code':nil},
  {'province_code':'lyo', 'border_province_code':'mar', 'border_coastal_code':nil},
  {'province_code':'lyo', 'border_province_code':'pie', 'border_coastal_code':nil},
  {'province_code':'lyo', 'border_province_code':'tus', 'border_coastal_code':nil},
  {'province_code':'lyo', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'lyo', 'border_province_code':'wes', 'border_coastal_code':nil},
  {'province_code':'lyo', 'border_province_code':'spa', 'border_coastal_code':nil},
  {'province_code':'mar', 'border_province_code':'spa', 'border_coastal_code':nil},
  {'province_code':'mar', 'border_province_code':'gas', 'border_coastal_code':nil},
  {'province_code':'mar', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'mar', 'border_province_code':'pie', 'border_coastal_code':nil},
  {'province_code':'mar', 'border_province_code':'lyo', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'iri', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'nat', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'bre', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'gas', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'naf', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'wes', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'spa', 'border_coastal_code':'nc'},
  {'province_code':'mid', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'mid', 'border_province_code':'por', 'border_coastal_code':nil},
  {'province_code':'mos', 'border_province_code':'stp', 'border_coastal_code':nil},
  {'province_code':'mos', 'border_province_code':'war', 'border_coastal_code':nil},
  {'province_code':'mos', 'border_province_code':'lvn', 'border_coastal_code':nil},
  {'province_code':'mos', 'border_province_code':'ukr', 'border_coastal_code':nil},
  {'province_code':'mos', 'border_province_code':'sev', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'boh', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'sil', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'ber', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'ruh', 'border_coastal_code':nil},
  {'province_code':'mun', 'border_province_code':'tro', 'border_coastal_code':nil},
  {'province_code':'naf', 'border_province_code':'tun', 'border_coastal_code':nil},
  {'province_code':'naf', 'border_province_code':'wes', 'border_coastal_code':nil},
  {'province_code':'naf', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'nap', 'border_province_code':'rom', 'border_coastal_code':nil},
  {'province_code':'nap', 'border_province_code':'apu', 'border_coastal_code':nil},
  {'province_code':'nap', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'nap', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'nat', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'nat', 'border_province_code':'cly', 'border_coastal_code':nil},
  {'province_code':'nat', 'border_province_code':'nrg', 'border_coastal_code':nil},
  {'province_code':'nat', 'border_province_code':'lvp', 'border_coastal_code':nil},
  {'province_code':'nat', 'border_province_code':'iri', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'nrg', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'swe', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'fin', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'stp', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'ska', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'nor', 'border_province_code':'bar', 'border_coastal_code':nil},
  {'province_code':'nrg', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'nrg', 'border_province_code':'bar', 'border_coastal_code':nil},
  {'province_code':'nrg', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'nrg', 'border_province_code':'nat', 'border_coastal_code':nil},
  {'province_code':'nrg', 'border_province_code':'edi', 'border_coastal_code':nil},
  {'province_code':'nrg', 'border_province_code':'cly', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'nrg', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'edi', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'yor', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'lon', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'hel', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'ska', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'bel', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'hol', 'border_coastal_code':nil},
  {'province_code':'nth', 'border_province_code':'den', 'border_coastal_code':nil},
  {'province_code':'par', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'par', 'border_province_code':'bre', 'border_coastal_code':nil},
  {'province_code':'par', 'border_province_code':'pic', 'border_coastal_code':nil},
  {'province_code':'par', 'border_province_code':'gas', 'border_coastal_code':nil},
  {'province_code':'pic', 'border_province_code':'par', 'border_coastal_code':nil},
  {'province_code':'pic', 'border_province_code':'bel', 'border_coastal_code':nil},
  {'province_code':'pic', 'border_province_code':'bre', 'border_coastal_code':nil},
  {'province_code':'pic', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'pic', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'pie', 'border_province_code':'mar', 'border_coastal_code':nil},
  {'province_code':'pie', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'pie', 'border_province_code':'tro', 'border_coastal_code':nil},
  {'province_code':'pie', 'border_province_code':'lyo', 'border_coastal_code':nil},
  {'province_code':'pie', 'border_province_code':'tus', 'border_coastal_code':nil},
  {'province_code':'por', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'por', 'border_province_code':'spa', 'border_coastal_code':'both'},
  {'province_code':'pru', 'border_province_code':'ber', 'border_coastal_code':nil},
  {'province_code':'pru', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'pru', 'border_province_code':'war', 'border_coastal_code':nil},
  {'province_code':'pru', 'border_province_code':'sil', 'border_coastal_code':nil},
  {'province_code':'pru', 'border_province_code':'lvn', 'border_coastal_code':nil},
  {'province_code':'rom', 'border_province_code':'tus', 'border_coastal_code':nil},
  {'province_code':'rom', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'rom', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'rom', 'border_province_code':'apu', 'border_coastal_code':nil},
  {'province_code':'rom', 'border_province_code':'nap', 'border_coastal_code':nil},
  {'province_code':'ruh', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'ruh', 'border_province_code':'bel', 'border_coastal_code':nil},
  {'province_code':'ruh', 'border_province_code':'hol', 'border_coastal_code':nil},
  {'province_code':'ruh', 'border_province_code':'kie', 'border_coastal_code':nil},
  {'province_code':'ruh', 'border_province_code':'bur', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'bul', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'bud', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'sev', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'bla', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'ukr', 'border_coastal_code':nil},
  {'province_code':'rum', 'border_province_code':'ser', 'border_coastal_code':nil},
  {'province_code':'ser', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'ser', 'border_province_code':'bud', 'border_coastal_code':nil},
  {'province_code':'ser', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'ser', 'border_province_code':'bul', 'border_coastal_code':nil},
  {'province_code':'ser', 'border_province_code':'gre', 'border_coastal_code':nil},
  {'province_code':'ser', 'border_province_code':'alb', 'border_coastal_code':nil},
  {'province_code':'sev', 'border_province_code':'mos', 'border_coastal_code':nil},
  {'province_code':'sev', 'border_province_code':'ukr', 'border_coastal_code':nil},
  {'province_code':'sev', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'sev', 'border_province_code':'bla', 'border_coastal_code':nil},
  {'province_code':'sev', 'border_province_code':'arm', 'border_coastal_code':nil},
  {'province_code':'sil', 'border_province_code':'ber', 'border_coastal_code':nil},
  {'province_code':'sil', 'border_province_code':'pru', 'border_coastal_code':nil},
  {'province_code':'sil', 'border_province_code':'war', 'border_coastal_code':nil},
  {'province_code':'sil', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'sil', 'border_province_code':'boh', 'border_coastal_code':nil},
  {'province_code':'sil', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'ska', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'ska', 'border_province_code':'swe', 'border_coastal_code':nil},
  {'province_code':'ska', 'border_province_code':'bal', 'border_coastal_code':nil},
  {'province_code':'ska', 'border_province_code':'nth', 'border_coastal_code':nil},
  {'province_code':'ska', 'border_province_code':'den', 'border_coastal_code':nil},
  {'province_code':'smy', 'border_province_code':'cons', 'border_coastal_code':nil},
  {'province_code':'smy', 'border_province_code':'ank', 'border_coastal_code':nil},
  {'province_code':'smy', 'border_province_code':'syr', 'border_coastal_code':nil},
  {'province_code':'smy', 'border_province_code':'arm', 'border_coastal_code':nil},
  {'province_code':'smy', 'border_province_code':'eas', 'border_coastal_code':nil},
  {'province_code':'smy', 'border_province_code':'aeg', 'border_coastal_code':nil},
  {'province_code':'spa', 'border_province_code':'por', 'border_coastal_code':'both'},
  {'province_code':'spa', 'border_province_code':'mid', 'border_coastal_code':'nc'},
  {'province_code':'spa', 'border_province_code':'wes', 'border_coastal_code':'sc'},
  {'province_code':'spa', 'border_province_code':'lyo', 'border_coastal_code':nil},
  {'province_code':'spa', 'border_province_code':'mar', 'border_coastal_code':nil},
  {'province_code':'spa', 'border_province_code':'gas', 'border_coastal_code':nil},
  {'province_code':'stp', 'border_province_code':'fin', 'border_coastal_code':nil},
  {'province_code':'stp', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'stp', 'border_province_code':'mos', 'border_coastal_code':nil},
  {'province_code':'stp', 'border_province_code':'bar', 'border_coastal_code':'nc'},
  {'province_code':'stp', 'border_province_code':'bot', 'border_coastal_code':'sc'},
  {'province_code':'stp', 'border_province_code':'lvn', 'border_coastal_code':nil},
  {'province_code':'swe', 'border_province_code':'nor', 'border_coastal_code':nil},
  {'province_code':'swe', 'border_province_code':'fin', 'border_coastal_code':nil},
  {'province_code':'swe', 'border_province_code':'den', 'border_coastal_code':nil},
  {'province_code':'swe', 'border_province_code':'bot', 'border_coastal_code':nil},
  {'province_code':'swe', 'border_province_code':'ska', 'border_coastal_code':nil},
  {'province_code':'syr', 'border_province_code':'arm', 'border_coastal_code':nil},
  {'province_code':'syr', 'border_province_code':'syr', 'border_coastal_code':nil},
  {'province_code':'syr', 'border_province_code':'eas', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'adr', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'tro', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'vie', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'bud', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'ser', 'border_coastal_code':nil},
  {'province_code':'tri', 'border_province_code':'alb', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'tus', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'rom', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'nap', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'wes', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'lyo', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'trn', 'border_province_code':'tun', 'border_coastal_code':nil},
  {'province_code':'tro', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'tro', 'border_province_code':'mun', 'border_coastal_code':nil},
  {'province_code':'tro', 'border_province_code':'boh', 'border_coastal_code':nil},
  {'province_code':'tro', 'border_province_code':'pie', 'border_coastal_code':nil},
  {'province_code':'tro', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'tun', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'tun', 'border_province_code':'ion', 'border_coastal_code':nil},
  {'province_code':'tun', 'border_province_code':'wes', 'border_coastal_code':nil},
  {'province_code':'tun', 'border_province_code':'naf', 'border_coastal_code':nil},
  {'province_code':'tus', 'border_province_code':'pie', 'border_coastal_code':nil},
  {'province_code':'tus', 'border_province_code':'ven', 'border_coastal_code':nil},
  {'province_code':'tus', 'border_province_code':'rom', 'border_coastal_code':nil},
  {'province_code':'tus', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'tus', 'border_province_code':'lyo', 'border_coastal_code':nil},
  {'province_code':'ukr', 'border_province_code':'mos', 'border_coastal_code':nil},
  {'province_code':'ukr', 'border_province_code':'sev', 'border_coastal_code':nil},
  {'province_code':'ukr', 'border_province_code':'rum', 'border_coastal_code':nil},
  {'province_code':'ukr', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'ukr', 'border_province_code':'war', 'border_coastal_code':nil},
  {'province_code':'ven', 'border_province_code':'rom', 'border_coastal_code':nil},
  {'province_code':'ven', 'border_province_code':'tus', 'border_coastal_code':nil},
  {'province_code':'ven', 'border_province_code':'pie', 'border_coastal_code':nil},
  {'province_code':'ven', 'border_province_code':'apu', 'border_coastal_code':nil},
  {'province_code':'ven', 'border_province_code':'tro', 'border_coastal_code':nil},
  {'province_code':'ven', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'vie', 'border_province_code':'boh', 'border_coastal_code':nil},
  {'province_code':'vie', 'border_province_code':'bud', 'border_coastal_code':nil},
  {'province_code':'vie', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'vie', 'border_province_code':'tri', 'border_coastal_code':nil},
  {'province_code':'vie', 'border_province_code':'tro', 'border_coastal_code':nil},
  {'province_code':'wal', 'border_province_code':'iri', 'border_coastal_code':nil},
  {'province_code':'wal', 'border_province_code':'lvp', 'border_coastal_code':nil},
  {'province_code':'wal', 'border_province_code':'yor', 'border_coastal_code':nil},
  {'province_code':'wal', 'border_province_code':'lon', 'border_coastal_code':nil},
  {'province_code':'wal', 'border_province_code':'eng', 'border_coastal_code':nil},
  {'province_code':'war', 'border_province_code':'pru', 'border_coastal_code':nil},
  {'province_code':'war', 'border_province_code':'lvn', 'border_coastal_code':nil},
  {'province_code':'war', 'border_province_code':'mos', 'border_coastal_code':nil},
  {'province_code':'war', 'border_province_code':'ukr', 'border_coastal_code':nil},
  {'province_code':'war', 'border_province_code':'gal', 'border_coastal_code':nil},
  {'province_code':'war', 'border_province_code':'sil', 'border_coastal_code':nil},
  {'province_code':'wes', 'border_province_code':'mid', 'border_coastal_code':nil},
  {'province_code':'wes', 'border_province_code':'spa', 'border_coastal_code':'sc'},
  {'province_code':'wes', 'border_province_code':'naf', 'border_coastal_code':nil},
  {'province_code':'wes', 'border_province_code':'tun', 'border_coastal_code':nil},
  {'province_code':'wes', 'border_province_code':'trn', 'border_coastal_code':nil},
  {'province_code':'wes', 'border_province_code':'lyo', 'border_coastal_code':nil},
  {'province_code':'yor', 'border_province_code':'edi', 'border_coastal_code':nil},
  {'province_code':'yor', 'border_province_code':'lvp', 'border_coastal_code':nil},
  {'province_code':'yor', 'border_province_code':'wal', 'border_coastal_code':nil},
  {'province_code':'yor', 'border_province_code':'lon', 'border_coastal_code':nil},
  {'province_code':'yor', 'border_province_code':'nth', 'border_coastal_code':nil}
])